import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Theme } from '@radix-ui/themes';

import '@radix-ui/themes/styles.css';
import '@/app/globals.css';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-inter',
  weight: 'variable',
  axes: ['opsz'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={inter.variable}
        style={{
          textRendering: 'optimizeLegibility',
        }}
      >
        <Theme accentColor="gray" grayColor="gray">
          {children}
        </Theme>
      </body>
    </html>
  );
}
